[package]
name = "chat_client"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
image = "0.24.7"
chat_lib = { path = "../chat_lib" }
