[package]
name = "transmuter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slug = "0.1.4"
csv = "1.3.0"
stanza = "0.3.0"
term_size = "0.3.2"
